sudo: required

language: bash
services: docker

before_install:
  - sudo apt update -y
  - sudo apt install realpath python python-pip -y
  - sudo apt install --only-upgrade docker-ce -y
  - sudo pip install docker-compose || true

script:
  - make build

before_deploy:
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin

deploy:
  provider: script
  script: make push
  on:
    branch: master    

after_script:
  - docker images
