sudo: required

language: bash
services: docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - make build

before_deploy:
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin

deploy:
  provider: script
  script: make push
  on:
    branch: master    

after_script:
  - docker images
